# Manual Backpropagation

In [1]:
# Import required modules
import numpy as np


### Implement the class for a node

In [ ]:
class layer:
    def __init__(self, numberOfInputs: int, numberOfNodes: int):
        self.weigths = np.random.rand(numberOfInputs, numberOfNodes)
        self.bias = np.random.rand(numberOfNodes)

    def getLayer(self):
        return(self.weigths)
    
    def compute(self, inputs: np.array) -> np.array:
        return  inputs * self.weigths + self.bias 
    
    def softmax(self) -> np.array:
        return output

### Implement the logic to setup a simple ANN

In [ ]:
class ANN:
    def __init__(self, numberOfLayers: int, inputVector: int, outputVector: int):
        self.LayerInput = layer(1, inputVector)
        self.LayerOutput = layer(1, outputVector)

        numberOfHiddenLayer = numberOfLayers - 2 
        for i = 1 : numberOfHiddenLayer

In [9]:
inputLayer = layer(numberOfInputs=1, numberOfNodes=8)
hiddenLayer = layer(numberOfInputs=8, numberOfNodes=3)
outputLayer = layer(numberOfInputs=3, numberOfNodes=8)


[[0.23446877 0.08482872 0.20630034 0.47906019 0.63395242 0.8306934 ]
 [0.99693206 0.49237252 0.28732987 0.04855673 0.94402079 0.91412825]
 [0.95481705 0.92610837 0.04597244 0.45385007 0.80668207 0.98560806]
 [0.86606076 0.14824707 0.53007661 0.11526339 0.03111949 0.66604593]
 [0.80594847 0.08659696 0.15277572 0.19461124 0.40795464 0.1803577 ]]


In [ ]:
# Input
input_value = [0, 0, 0, 1, 0, 0, 0, 0]
correct_output_value = input_value